version: "3"

services: 
    flask:
        build: ./flask
        container_name: heyvolleyball_flask
        restart: always
        environment: 
            - APP_NAME=heyvolleyballTest
        expose:
            - 8000
        
    nginx:
        build: ./nginx
        container_name: heyvolleyball_nginx
        restart: always
        ports:
            - "5000:5000"